### ISSUE TITLE
Image Tracking TREX demo BUG

### ISSUE THREAD

**Issue by shubhamraghav1** [AR-js-org/AR.js#187]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
The Trex model is not in the center of NFT marker

**If the current behavior is a bug, please provide the steps to reproduce.**
Check the example given in AR js image tracking docs

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**
The Trex model should be in the center of NFT marker

**If this is a feature request, what is motivation or use case for changing the behavior?**
Its a bug

**Comment by arsandev** [comment]
Probably not a bug. You can set position of model by ``position`` attribute:

```html
      <a-entity
        gltf-model="https://arjs-cors-proxy.herokuapp.com/https://raw.githack.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex/scene.gltf"
        scale="5 5 5"
        position="50 150 0" <!-- your model position (X Y Z) -->
      >
```

**Comment by shubhamraghav1** [comment]
But there center of rotation are still different, like if you move around a bit placing Trex on your marker then it changes its position when u rotate a bit.
i,e. the center of rotation of 3d model is not same as center of nft, like it was in marker

**Comment by shubhamraghav1** [comment]
@nicolocarpignoli please check

**Comment by Varnani** [comment]
It's most likely related to this problem: https://github.com/AR-js-org/AR.js/issues/72

Does your phone have multiple cameras? If so, the browser might be using the wrong camera. I have OnePlus 7T and Chrome uses the telephoto camera which causes this rotational behaviour.

Sadly this is a WebRTC issue, not a AR.js. Chrome does not recognize the main camera on some phones at all. You can test this by going to https://webrtc.github.io/samples/src/content/devices/input-output/ and changing the camera source. There's only one camera for me, which is the telephoto one. This causes 2 major problems: Jittery tracking due to reduced camera quality and tracking mismatch between camera orientation and marker position.

I guess we have to wait for WebRTC implementations to improve.

**Comment by 93Dennis** [comment]
It was asked a couple of times by now. Here is the original issue: #4 

Unfortunately, NFT is still not production ready :/

**Comment by nicolocarpignoli** [comment]
Duplicate
