### ISSUE TITLE
trex example not working - throwing "Error in loading marker on Worker"

### ISSUE THREAD

**Issue by jaylenwang7** [AR-js-org/AR.js#249]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using the image tracking trex example [here](https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/) it doesn't pass the loading page and throws the "Error in loading marker on Worker" message. It seems like this is related to the recent change to use pathing instead of a URL for the NFT marker.

**If the current behavior is a bug, please provide the steps to reproduce.**
Trying to load [this](https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/) page.

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
@jaylenwang7 yes it is related to PR #248 but we can't do so much at the moment. The NFT examples won't work for now. It's a gh-pages issue; in order to work the nft examples require in the path of the resources an extra `/AR.js/` see the `https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/` it in the but we can't add this because runnong in localhost or other host will break. we solved in the past serving with a proxy `https://arjs-cors-proxy.herokuapp.com/https://raw.githack.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex/trex-image/trex` but this is not possible anymore. But you can run the exmples in your local machine, Did you tested? 
We could fix this creating another branch and fixing the paths but this is not optimal in my opinion, the solution should be add an extra option for the path as i did for example for our webarkit/ARnft we add the addPath:
https://github.com/webarkit/ARnft/blob/be2944db4bf61896cdbdd1435942d60ce489b8c0/src/utils/Worker.js#L38
to fix this kind of issues, but it is not a priority at the moment.

**Comment by kalwalt** [comment]
fixed link https://ar-js-org.github.io/.github/profile/aframe/examples/image-tracking/nft/ #529
