### ISSUE TITLE
Typo in component-anchor.js?

### ISSUE THREAD

**Issue by JohnGrime** [AR-js-org/AR.js#310]
**Do you want to request a *feature* or report a *bug*?**

Report a bug (potential?)

**What is the current behavior?**

In `AR.js/aframe/src/component-anchor.js`, line 118 reads:

https://github.com/AR-js-org/AR.js/blob/aaad9847f67a4738b00724c38d9f501d78e0a8af/aframe/src/component-anchor.js#L118

The use of `_this.data.minCondidence` looks like a typo to me, and I can't find any reference to a `minCondidence` member elsewhere.

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**Please mention other relevant information such as the browser version, Operating System and Device Name**

N/A

**What is the expected behavior?**

I guess I'd expect line 188 instead to read:

`markerParameters.minConfidence = _this.data.minConfidence;`

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
Yes, @JohnGrime  you are right we have fixed in ES6 branch https://github.com/AR-js-org/AR.js/blob/d998a442303b042107c26de8639df75900cef350/aframe/src/component-anchor.js#L123 see PR  https://github.com/AR-js-org/AR.js/pull/116 but not in master nor in dev yet. I will see if make a fix or waiting to merge the ES6 into dev ( we are very close!).
Anyway tahnks for reporting the bug!

**Comment by kalwalt** [comment]
The fix for this is merged on the dev branch and soon i hope to merge into the master. Closing this issue, and thanks again @JohnGrime  for reporting.
