### ISSUE TITLE
The "Image tracking" live example app doesn't work. 

### ISSUE THREAD

**Issue by ShacharWeis** [AR-js-org/AR.js#364]
https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/

It shows the camera view but darkened and "Loading please wait" message that doesn't go away. 
The sample image doesn't track.

**Comment by kalwalt** [comment]
@ShacharWeis some examples or probably all examples are affected by path issues. Because github pages need a different path for the resources, i think that will stay as it is. It will require to change the path of  the resources but they will not work on localhost. We could think in a future a different solution, hosting the examples on Ar.js official website but this require pay the hosting, maintaining and so on. Not an option that we can do now.

**Comment by jerrylance** [comment]
This problem has bothered me for a long time, and now it has finally been solved.
View the source code of image descriptors file loaded by ar.js (aframe-ar-nft.js file)

        // after the ARController is set up, we load the NFT Marker
        var regexM = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#()?&//=]*)/igm
        var reM = regexM.test(msg.marker);
        if (reM == true) {
            console.log('msg.marker=', msg.marker);
            nftMarkerUrl = msg.marker;
        } else if (reM == false) {
            console.log('basePath=', basePath);
            nftMarkerUrl = basePath + '/' + msg.marker;
        }
        console.log('nftMarkerUrl=', nftMarkerUrl);
        
        ar.loadNFTMarker(nftMarkerUrl, function (markerId) {
            ar.trackNFTMarkerId(markerId);
            postMessage({ type: 'endLoading' })
        }, function (err) {
            console.log('Error in loading marker on Worker', err)
        });
As can be seen from the source code, if we specify that the URL of NFT is provided in the form of domain name, such as the URL of the official demo https://arjs-cors-proxy.herok... , then directly use the URL we passed in;
Otherwise, use basepath + the URL we passed in.
Ar.js (actually A-frame) is different in handling NFT URL and model URL. There are two correct configuration methods:
1) HTML deployed web services must support domain name access, and the URL of NTF must be configured as the complete domain name access path where the image descriptors file is located;
2) HTML deploys local web services, which are accessed by 127.0.0.1 or service IP address. The URL paths of NTF and model must be configured as relative paths. The path of NFT must contain the web service name, while the URL path of mode does not contain the web service name. 
Here is an correct example of No.2, using Tomcat at https://localhost:8443/AR.js/index.html

        <a-nft
            type='nft' url='AR.js/aframe/examples/image-tracking/nft/trex/trex-image/trex'
            smooth='true' smoothCount='10' smoothTolerance='0.01' smoothThreshold='5'>
            <a-entity
                gltf-model='aframe/examples/image-tracking/nft/trex/scene.gltf'
                scale="5 5 5"
                position="150 300 -100"
                >
            </a-entity>
        </a-nft>

**Comment by kalwalt** [comment]
@jerrylance yes that's it! The problem occurs also with gh-pages while require a different path for some resources. For example now the three.js nft example fail to load the NFT marker because the worker need a different path. If you run that code instead in localhost will work without issue. One thing to help: in dev console look into the Network tab and check the path of resources this will give you an advice for solving the issue.

**Comment by jerrylance** [comment]
@kalwalt Indeed, thank you for your help.

**Comment by qianxifu** [comment]
@jerrylance 你好我是以web服务的方式部署的，看了浏览器控制台network的Network Tab 资源都是可以访问到的。还是没有显示3d模型

<script
  src='https://cdn.jsdelivr.net/gh/aframevr/aframe@1c2407b26c61958baa93967b5412487cd94b290b/dist/aframe-master.min.js'></script>
<script src='./aframe-ar-nft.js'></script>


<body style='margin : 0px;'>
  
  
  <a-scene vr-mode-ui='enabled: true;' renderer="logarithmicDepthBuffer: true; precision: medium;" embedded
    arjs='trackingMethod: best; sourceType: webcam; debugUIEnabled: true;'>

    
    

    <a-nft type='nft'
      url='https://4619l0h415.xicp.fun/AR.js-master/aframe/examples/image-tracking/nft/trex/girl-image/girl'
      smooth='true' smoothCount='10' smoothTolerance='0.01' smoothThreshold='5'>

      <a-entity gltf-model='https://4619l0h415.xicp.fun/AR.js-master/aframe/examples/image-tracking/nft/robot.glb'
      position="-2 -10 0"
      rotation="-90 0 0"
      scale="0.5 0.5 0.5">
      </a-entity>

    </a-nft>
    <a-entity camera></a-entity>
  </a-scene>
</body>

**Comment by jerrylance** [comment]
这是使用windos环境下tomcat部署的，利用笔记本摄像头识别的效果。这个项目主要问题就是路径的问题，有的带项目名，有的不带，参考我发你文件的路径部分。主目录为AR.js-dev，html文件见附件








&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AR-js-org/AR.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AR-js-org/AR.js] The "Image tracking" live example app doesn't work.  (Issue #364)





 
@jerrylance 你好我是以web服务的方式部署的，看了浏览器控制台network的Network Tab 资源都是可以访问到的。还是没有显示3d模型
 <script   ***@***.***/dist/aframe-master.min.js'&gt;</script&gt; <script src='./aframe-ar-nft.js'&gt;</script&gt;          <!-- use rawgithack to retrieve the correct url for nft marker (see 'pinball' below) --&gt; <!-- <a-nft type='nft' url='./trex/trex-image/trex' smooth='true' smoothCount='10' smoothTolerance='0.01' smoothThreshold='5'&gt;   <a-entity gltf-model='https://caitoujun.oss-cn-shenzhen.aliyuncs.com/robot.glb' scale="0.5 0.5 0.5" position="0 0 0"&gt;   </a-entity&gt; </a-nft&gt; --&gt; <a-nft type='nft'   url='https://4619l0h415.xicp.fun/AR.js-master/aframe/examples/image-tracking/nft/trex/girl-image/girl'   smooth='true' smoothCount='10' smoothTolerance='0.01' smoothThreshold='5'&gt;   <a-entity gltf-model='https://4619l0h415.xicp.fun/AR.js-master/aframe/examples/image-tracking/nft/robot.glb'   position="-2 -10 0"   rotation="-90 0 0"   scale="0.5 0.5 0.5"&gt;   </a-entity&gt; </a-nft&gt; <a-entity camera&gt;</a-entity&gt;

**Comment by kalwalt** [comment]
For anyone interested i changed the live link in the Readme, now is served at https://ar-js-org.github.io/.github/profile/aframe/examples/image-tracking/nft/ see commit https://github.com/AR-js-org/AR.js/commit/8609ac9689e0e9a4c0bfc44ea6ca7ae795b1da81 #529

**Comment by juanpenk** [comment]
Hello! I am trying to create my own example using the same code as the one in the documentation, on local works fine, but when i go live, either using github or digitial ocean for hosting the descrption files for the nft,  i get stuck on the loading screen so i assume there is something wrong in the path, for the github pages test i used https://juanpenk.github.io/SanMiguelChroma/arjs3-image-tracking as the path to the nft.

Hope you can give me some advice on what to do! As I cannot find helpful information i can understand. Thanks.
