### ISSUE TITLE
Shifted Position of 3D-Objects using NFT

### ISSUE THREAD

**Issue by Jeggle-s** [AR-js-org/AR.js#42]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When i'm using AR.js with A-Frame and NFT, the 3D-Objects keep changing it's position when I move the camera. 

**If the current behavior is a bug, please provide the steps to reproduce.**
1.) Run the NFT example in the A-Frame Folder of AR.js
2.) Move your Camera (phone) and keep an eye on the feet of the dinosaur.
3.) The Model won't be at the same position, as when it first was rendered.

As I mentioned, you can use the NFT example in the A-Frame Folder of this repo (https://github.com/AR-js-org/AR.js/tree/master/aframe/examples/image-tracking/nft)

I took two screenshots for comparison, first is after the markr was found and second after I moved the camera a bit:
<img src="https://user-images.githubusercontent.com/38358202/76067869-6acd7300-5f90-11ea-99e5-adc9aa38007d.jpg" alt="alt text" width="100" height="200">

<img src="https://user-images.githubusercontent.com/38358202/76067923-80429d00-5f90-11ea-9b2a-8785a1bd3cec.jpg" alt="alt text" width="100" height="200">

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Phone: Samsung Galaxy A3 2017
OS: Android 8.0.0
Browser: Chrome 80.0.3987.119

**What is the expected behavior?**
The Object stays at the same position, no matter if I move the camera or not.

**Comment by kalwalt** [comment]
Someone already posted this problem on my repo https://github.com/kalwalt/jsartoolkit5/issues/31 I don't think that is a bug, the problem is that the algorithm has not multithreading as the original C++ version and so it's not updating so fast, and the consequence is that the model not follows so quickly the changes. You can compare the simple example with a sphere and that one with a complex model (see the jsartolkit5 examples), and you will see a noticeable difference. We would improve this for sure... :slightly_smiling_face: but no eta at the moment on this topic.

**Comment by nicolocarpignoli** [comment]
@Jeggle-s did you solved?

**Comment by Jeggle-s** [comment]
@nicolocarpignoli No, the shift of content after I#m moving the phone could not be solved. But as kalwalt mentions it's a problem with the speed of the algorithm. As of now, I will close this issue.

**Comment by kalwalt** [comment]
> @nicolocarpignoli No, the shift of content after I#m moving the phone could not be solved. But as kalwalt mentions it's a problem with the speed of the algorithm. As of now, I will close this issue.

Maybe could be speed up in a future with SIMD compilation, but i don't know when it will  be possible.
