### ISSUE TITLE
The live demo website is loading forever, image-tracking/nft/trex/trex-image/trex.fset 404

### ISSUE THREAD

**Issue by albirrkarim** [AR-js-org/AR.js#529]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

I access this url, with Samsung galaxy a53

https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/

then it loading forever like this

![WhatsApp Image 2023-03-21 at 08 12 00](https://user-images.githubusercontent.com/29292018/226497624-df3ca1be-7118-4e43-a0a1-bd3bb9dc423b.jpeg)

then I inspect element and got this 404

<img width="1306" alt="Screenshot 2023-03-21 at 08 07 22" src="https://user-images.githubusercontent.com/29292018/226497659-09b07d2d-d215-430a-96bf-69233d1ee45e.png">

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/29292018/226497732-96afceaa-24e4-4802-921e-5cf6e0c705ce.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

Device:
Mac book air m1, ipad pro m1, Samsung galaxy a53

**What is the expected behavior?**

The demo is work

**Comment by zoebachman** [comment]
Same issue!

**Comment by kalwalt** [comment]
The problem is that we use `gh-pages` for the examples, but the examples taht works fine on localhost need another path for the resources. We can setup the path with jsdndeliveror raw.githack services, but this is unconfortable for developing. Really. Because you need to change the path for every example. The solution is to store the examples in another repository. My idea is to create a new web page for the AR-js-org and store the examples there.It's possible to create a repo AR-js-org/AR-js_org as entry point for the organization. @nickw1 if have time i will do this.
In the meantime, apologize for the inconvenience, but we are a very little team at the moment. It's difficult to find the time for that kind of improvements.

**Comment by ms2296** [comment]
@kalwalt so what do you best recommend to try out the demo? that we use gh-pages or another/normal hosting service?

**Comment by kalwalt** [comment]
> @kalwalt so what do you best recommend to try out the demo? that we use gh-pages or another/normal hosting service?
I will try to find a solution next week i have not time at the moment.

**Comment by kalwalt** [comment]
To everyone here: Please, try this link https://ar-js-org.github.io/.github/profile/aframe/examples/image-tracking/nft/ if it is ok i will update that one in the AR.js Readme.md

**Comment by commandiron** [comment]
> To everyone here: Please, try this link https://ar-js-org.github.io/.github/profile/aframe/examples/image-tracking/nft/ if it is ok i will update that one in the AR.js Readme.md

it is working.

**Comment by ms2296** [comment]
yes, can also confirm that it's working

**Comment by kalwalt** [comment]
Ok, thank you for testing @commandiron @ms2296 i will replace the link in the Readme with this one.

**Comment by kalwalt** [comment]
I just updated the links in the [Readme.md](https://github.com/AR-js-org/AR.js/blob/master/README.md) https://github.com/AR-js-org/AR.js/commit/8609ac9689e0e9a4c0bfc44ea6ca7ae795b1da81 NFT amd marker example.
