### ISSUE TITLE
[location-based]: Use metre-based geographical projections for GPS and feature positions?

### ISSUE THREAD

**Issue by nickw1** [AR-js-org/AR.js#70]
**Do you want to request a *feature* or report a *bug*?**

Feature

**If this is a feature request, what is motivation or use case for changing the behavior?**
Really like the look of AR.js and would like to use it for my (currently) Android-based outdoor navigation app "Hikar" which shows roads and paths from OpenStreetMap as well as virtual signposts in AR.

I'm wondering whether it would make things simpler in these sorts of use-cases which deal with more complex geographical data to use a different projection to store the GPS and feature coordinates.

Rather than setting the origin to the original GPS location and calculating the distance in metres from that origin to each geographical feature, the absolute coordinates of both the current GPS position and the geographical features could be stored in a metre-based projection such as Spherical Mercator (epsg:3857) or others. The projected coordinates could then be directly used as the OpenGL/A-Frame world coordinates.

This would mean that the current camera position would typically be well away from the origin (for example, in Spherical Mercator lat 51.05, lon -0.72 is approximately x = -80000, y =  6600000, giivng a camera position of x=80000, z=-6600000. However as far as I am aware this would not cause problems, and seems to work OK in tests.

Not saying this is definitely the best approach but just my thoughts, having taken this approach with my Hikar app.  Using a metre-based projection would also facilitate easy fetching and caching of tiled vector data from an API, such as the 'xyz' based tiling system first popularised by Google Maps and used also in OpenStreetMap.

I have already developed a proof-of-concept version of the gps-camera component in my fork of the repo at
https://github.com/nickw1/AR.js/tree/dev/aframe/src/location-based

See the gps-projected-camera component. It's using Spherical Mercator at present but could potentially use other projections.
For an example of how this could be used in a real project see
https://gitlab.com/nickw1/hikar.org/-/tree/master/webapp
(note, this isn't really working fully yet - though it will in theory overlay the OpenStreetMap data on the AR.js camera feed)

**Comment by nicolocarpignoli** [comment]
@nickw1 can you please provide a live working URL other than the code? 

Looks interesting :)

**Comment by nickw1** [comment]
@nicolocarpignoli thanks!

I do have a live URL: https://hikar.org/webapp/

Try on a mobile device and it should download OpenStreetMap data for your local area and render it on the device. Limited status updates at the moment, and you should download using wifi as it'll be rather slow on phone networks.

Limited testing at the moment due to the virus restrictions, but from what I make out from testing indoors (I will go out for short walk later) it appears to work. Only tested on a Pixel 3 so far, and the rendering is currently rather glitchy.

**Comment by nickw1** [comment]
@nicolocarpignoli Sorry - to update - I have been out for a short walk to test it and am encountering some bugs with  positioning the data so it's not quite ready to test yet... but hopefully you get the idea of what I'm trying to do. Will keep you posted with updates.

**Comment by nickw1** [comment]
@nicolocarpignoli https://hikar.org/webapp should work now. It's a bit jittery but it essentially works :-)

**Comment by nicolocarpignoli** [comment]
It works good on my Huawei! Can u show me the code? It's on Github?

**Comment by nicolocarpignoli** [comment]
Okay I guess it's the repository posted above

**Comment by nicolocarpignoli** [comment]
So @nickw1 It looks very promising. Augmented content is very stable. 

I have tried your example and also tried your component on AR.js location-based example.

In my opinion it has a great potential, but maybe as an additional approach. The idea to name is as 'projected' camera and to have both cameras is probably the best way.

With your example, the result is very good and content is stable.
Using it with AR.js default examples, it gives wrong positioning of objects, as they seems to remain always visible if I put down the phone, and in general does not respect coordinates of content.

It's hard to explain: to understand you can try this example with latitude/longitude near you, and user your camera instead of default one, and you will see and understand what I mean (try to look around and put down the phone, for example): https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/location-based/always-face-user/index.html

Anyway, again, I think that makes a lot of sense to add this new component.

On your example with open street map, are you able to put the 'map' lower on y axis? You should be able to do that changing position of gps-entity-place component like this, for example 
`<blablabla gps-entity-place="blablabla" position="0 -20 0">`

It will be curious to make it lower so you can see it better, and you will actually have a REAL map, very stable, lookin through the camera!

PS. if you transfer this repo on Github, I can give you an help and a closer look ;)

**Comment by nickw1** [comment]
@nicolocarpignoli thanks for your comments! 

I have actually continued to work on this today, and have adapted gps-entity-place to work with the new projected camera, component name predictably enough...gps-projecred-entity-place :-)
Updates can be found on my github fork, which I've cleaned up by squashing some commits.

Are you happy for me to submit a PR? I have put my code in an 'experimental' directory within the location-based directory so that it's cleanly separated from the original code.

Entity-places now work: this can be tested by 'faking' a location via
https://hikar.org/webapp/?lat=51.049&lon=-0.723

I have added two a-boxes, one red one yellow, close to this location, with gps-projected-entity-place components added. These have latitude, longitude and elevation parameters.

Yes, I can drop the y axis, I've already done this by 5m in my code but can drop further.
I'll move my repo to github :-)

**Comment by nickw1** [comment]
@nicolocarpignoli My repo now on github:
https://github.com/nickw1/hikar.org

**Comment by nicolocarpignoli** [comment]
yes please:

* do not use separate folder, put these new components under 'location-based' folder directly
* create a PR against 'dev' from your repo

We can continue discuss/testing on the PR :) Thanks again

**Comment by nickw1** [comment]
@nicolocarpignoli ok have created the PR. Have moved the components as you requested.

**Comment by nicolocarpignoli** [comment]
@nickw1 Ok I have created another PR to finish the feature addition, will tag you there

**Comment by nicolocarpignoli** [comment]
merged. thanks!

**Comment by nicolocarpignoli** [comment]
@nickw1 can you please give me your email? I'd like to add you to AR.js Slack if you are ok with that :) Lot of people interested on your Location based work.

**Comment by nickw1** [comment]
@nicolocarpignoli OK will do, will send email to yoiur gmail address.
