### ISSUE TITLE
Readme refactor for v3

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/AR.js#8]

**Comment by Carnaux** [comment]
I can help!! How the new structure is going to be?

**Comment by kalwalt** [comment]
We could add in the Readme a link to the examples. The page https://ar-js-org.github.io/AR.js/ is online but, if you navigate to https://ar-js-org.github.io/AR.js/three.js/examples/ you get a 404 page because no index.html file is provided.  There is a link to [Examples](https://jeromeetienne.github.io/AR.js-docs/misc/EXAMPLES.html) but point to the old website.

**Comment by nicolocarpignoli** [comment]
@kalwalt absolutely. thanks for offering help @Carnaux , much appreciated. you could look into that !

**Comment by nicolocarpignoli** [comment]
also, I will look into adding a documentation for custom events:

three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: arjs-video-loaded
three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: camera-error
three.js/src/threex/threex-artoolkitsource.js and three.js/build/ar.js: camera-init
aframe/src/location-based/gps-entity-place.js: gps-entity-place-update-positon
aframe/src/location-based/gps-entity-place.js: gps-entity-place-added
aframe/src/location-based/gps-camera.js: gps-camera-origin-coord-set
aframe/src/location-based/gps-camera.js: gps-camera-update-position
aframe/examples/places-name/places.js: gps-entity-place-loaded
aframe/examples/marker-events.html: markerFound
aframe/examples/marker-events.html: markerLost

coming from issues:  https://github.com/jeromeetienne/AR.js/issues/567
