### ISSUE TITLE
Accessing Marker Parametrization of the Scene at Marker Discovery?

### ISSUE THREAD

**Issue by evaristoc** [AR-js-org/AR.js#87]
Hi everyone,

Is there a way to access the values for the viewMatrix, resolution, sizes of marker (w & h), etc from all marker-based applications at the time the marker is discovered and along an animation?

**Comment by kalwalt** [comment]
@evaristoc you can acces at these values /infos  all the time with an event listener, because AR.js is based on Jsartoolkit5, with Jsartoolkit5 you can :

```javascript
arController.addEventListener('getMarker', function (event) {
  var data;
  data = event.data;
  console.log(data);
 })
```
see my [stackoverflow answer](https://stackoverflow.com/questions/61239107/how-to-get-marker-position-x-y-ar-js/61249888#61249888) for the three.js version is simpler for Aframe a bit more complex.

**Comment by evaristoc** [comment]
Thanks, @kalwalt !

And just a quick question: what would be the difference between setting the THREEx.ArMarkerControls "changeMatrixMode" parameters `viewModelMatrix` and `cameraTransformationMatrix`? I couldn't find any information about that in the documentation.

**Comment by evaristoc** [comment]
I will ask the above question later. Thanks! Closing this one.
